#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Sharing_GS
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=800gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
#SBATCH --nodelist=xcng1
srun python G_send_to_S.py