#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=sg
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --ntasks=1
srun python S_evaluate_G_1.py