#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=G_unknown
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodes=2-5
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=50
python grun.py