#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Sharing_SS
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=120gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
#SBATCH --exclude=xcng1
which python
python S_send_to_S.py