#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Rank_based_SG
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --ntasks=1
#SBATCH --exclude=xcng0,xcnf0
srun python S_send_to_G_rank_visibility.py