#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=mixed_share_3
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --nodelist=xcng[0-1],xcnf[15-22,24,26-29]
#SBATCH --ntasks=1
srun python GS_mixed_sharing_3.py