#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=FoolingG_12
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
srun python grun_12.py