#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --job-name=T
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=10gb
#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --nodelist=xgph18

python trun.py