#!/bin/bash
#SBATCH --time=00:30:00
#SBATCH --job-name=Draw
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=medium
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
python drawer.py