#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --job-name=G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=10gb
#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --nodelist=xgph10

python grun.py