#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=mgs
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
srun python G_send_to_S_1.py