#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Parallel
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=400gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=64
#SBATCH --ntasks=1
srun python S_send_to_S_2.py