#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=22
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=400gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=80
#SBATCH --ntasks=1
srun python G_send_to_S_4.py