#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=RanTP20
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=52
#SBATCH --ntasks=1
python trun.py