#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Cache_1
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=400gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --ntasks=1
srun python cache_run_1.py