#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Parallel
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
srun python srun_4.py