#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=gs_team
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
source ~/anaconda3/etc/profile.d/conda.sh
conda activate py39
python gsrun.py