#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=DepthComplexity3
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
#SBATCH --exclude=xcng[0-1]
srun python GS_mixed_sharing.py