#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Evaluating_GG
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=500gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
#SBATCH --exclude=xcng[0-1]
srun python G_evaluate_G.py