#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Evaluating_SG
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=800gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
#SBATCH --exclude=xcng[0-1]
srun python S_evaluate_G.py