#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Timing_GG
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --ntasks=1
#SBATCH --exclude=xcng0,xcnf0
srun python G_send_to_G_visibility_timing.py