#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Cache_2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=40
#SBATCH --ntasks=1
python cache_run_0.2.py