#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Cache_2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=100
#SBATCH --ntasks=1
# Activate the Conda environment with the desired Python version
source ~/anaconda3/etc/profile.d/conda.sh
conda activate py39

python cache_run_2.py