#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Cache_2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --exclude=xcng0,xcng1
srun python cache_run_2.py