#!/bin/bash
#SBATCH --time=00:10:00
#SBATCH --job-name=S-test
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=10gb
#SBATCH --partition=standard
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
python Specialist.py