#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=Baseline_S12
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=medium
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
python srun.py