#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=GG_5
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
python G_evaluate_G_5.py