#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=gg3_Priority
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
python ggrun_3.py