#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=G12
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
python grun.py